#
# Copyright 2022-2024 Martin Goellnitz
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program. If not, see <http://www.gnu.org/licenses/>.
#
name: Build JFileSync3

on:
  push:
    branches:
    - master
    - 3.*
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: provocon/java:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build with Gradle
        run: ./gradlew -PossindexUser=${{secrets.OSS_INDEX_USER}} -PossindexToken=${{secrets.OSS_INDEX_TOKEN}} clean audit build

      - name: Extract Package
        run: unzip -q build/distributions/*.zip

      - name: Archive Package
        uses: actions/upload-artifact@v4
        with:
          name: JFileSync3-${{ github.ref_name }}
          path: JFileSync3/*
          retention-days: 5
